### ISSUE TITLE
Test should be augmented or oryginal?

### ISSUE THREAD

**Issue by piotrusieg** [grudloff/Salomon2017Replication#1]
Hey!
Nice piece of code.
Does test set should have data from augmented or from oryginal dataset, as you mentioned in "preprocessing_augmented.py"?
I see that you use data from original dataset, but because of "#TODO" section with that question I want to be sure.
Thanks!

**Comment by grudloff** [comment]
Hello, thanks for the compliment! I don't know what the authors did on the original publication, but as long as you don't modify the validation it should be ok regarding usk8 directives. If you want you can try out using the augmented data as testing, you just need to modify `load_dir` for `augmenter_load_dir` in the test data loading.
